---
root: true

env:
  browser: true
  es2022: true

globals:
  # app details
  APP: readonly
  AUTHOR_NAME: readonly
  AUTHOR_URL: readonly
  HOMEPAGE: readonly
  LICENSE: readonly
  VERSION: readonly
  # service worker
  SW_URL: readonly
  # vue 3.2 syntax
  defineEmits: readonly
  defineProps: readonly
  defineExpose: readonly
  withDefaults: readonly

extends:
  - plugin:import/recommended
  - plugin:jsdoc/recommended
  - plugin:vue/vue3-recommended
  - airbnb-base

plugins:
  - import
  - jsdoc
  - vue

rules:
  arrow-parens:
    - error
    - as-needed
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
    - always
  import/extensions:
    - error
    - ignorePackages
    - js: always
      vue: always
  indent:
    - error
    - 2
    - SwitchCase: 1
  jsdoc/no-undefined-types:
    - error
    - definedTypes:
        - HttpArchive
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - 120
  no-console: error
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-underscore-dangle:
    - error
    - allow:
        - _error
        - _harviewer
        - _webSocketMessages
  quotes:
    - error
    - double
  semi:
    - error
    - always
  vue/multi-word-component-names:
    - error
    - ignores:
      - Shell
      - Footer
      - Modal

overrides:
  - files:
      - "*.vue"
    rules:
      indent: 0
      vue/script-indent:
        - error
        - 2
        - baseIndent: 1
          switchCase: 1
  - files:
      - "*.html"
    rules:
      vue/comment-directive: 0
