---
root: true

env:
  browser: true
  es2021: true

globals:
  DEBUG: readonly
  # app details
  APP: readonly
  AUTHOR_NAME: readonly
  AUTHOR_URL: readonly
  HOMEPAGE: readonly
  LICENSE: readonly
  VERSION: readonly
  # service worker
  SW_URL: readonly
  # vue 3.2 syntax
  defineEmits: readonly
  defineProps: readonly
  defineExpose: readonly
  withDefaults: readonly

extends:
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsdoc/recommended
  - plugin:vue/vue3-recommended
  - airbnb-base

plugins:
  - import
  - jsdoc
  - vue

settings:
  import/resolver: webpack

rules:
  arrow-parens:
    - error
    - as-needed
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
    - always
  import/extensions:
    - error
    - ignorePackages
    - js: never
      vue: never
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - 120
  no-console: error
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  quotes:
    - error
    - double
  semi:
    - error
    - always

overrides:
  - files:
      - "*.vue"
    rules:
      indent: 0
      vue/script-indent:
        - error
        - 2
        - baseIndent: 1
          switchCase: 1
  - files:
      - "*.html"
    rules:
      vue/comment-directive: 0
